### ISSUE TITLE
Suggestion: Alt forms

### ISSUE THREAD

**Issue by RealCornQueen** [pokedextracker/pokedextracker.com#449] opened 2022-03-03 15:46 UTC
Add alternate forms for, Vivlion, Deerling/Sawsbuck, Unown etc

and ability to toggle shiny locked pokemon, and disable gmax forms

**Comment by Azekthi** [comment] 2022-03-20 06:52
Forms handling: #256 

Shiny lock: #277

**Comment by HL971** [comment] 2023-01-22 19:54
Scarlet/Violet Has 3 forms of Tauros, the tracker only has one

**Comment by ami** [comment] 2023-06-04 02:14
closing as this is a dupe of the two tickets @Azekthi mentioned above.

**Closed by ami** 2023-06-04 02:14 UTC
