### ISSUE TITLE
Add different language

### ISSUE THREAD

**Issue by Lutenus** [pokedextracker/pokedextracker.com#380] opened 2020-06-12 20:38 UTC
It would be nice to track your mons in your native language (or if you want to trade but don‘t know which one the other player is asking fore).
Willing to provide for german

**Comment by ami** [comment] 2020-06-17 22:09
thanks for reaching out @Lutenus! closing this issue as it is a duplicate of #146

**Closed by ami** 2020-06-17 22:09 UTC
