### ISSUE TITLE
Suggestion: Different coloured highlight options instead of just "Caught" and "Not Caught"?

### ISSUE THREAD

**Issue by Rockin132** [pokedextracker/pokedextracker.com#453] opened 2022-05-13 12:34 UTC
I currently have duplicates of every dex on my tracker for example, one for tracking my living dex, and one for tracking my living dex with relation to the pokemon in the living dex having the correct OT (my name),

Some pokémon in my living dex are from Events and therefore cannot legally have my OT. It helps me to keep track of these so I have a list of what I still need to get with my correct OT and which ones I have already completed and have the correct OT.

It'd be nice if it were possible to set "Green" as Obtained on Pokedex Tracker, No colour as not obtained, and maybe like "Yellow" as Obtained but with caveats. That way I could have just one dex on Pokedex Tracker instead of duplicating each dex, and I would be able to keep a mental note that Green = Correct OT and Yellow = Obtained by not the correct OT.

An odd use case, I know. I suppose this could be solved with the suggested notes function from Issue #266 instead?

**Comment by ami** [comment] 2023-06-04 02:13
closing, dupe of: https://github.com/pokedextracker/pokedextracker.com/issues/231

**Closed by ami** 2023-06-04 02:13 UTC
