### ISSUE TITLE
feature request: add older Pokédex

### ISSUE THREAD

**Issue by SuperFola** [pokedextracker/pokedextracker.com#402] opened 2021-04-03 11:31 UTC
It would interesting for "retro" players to add the Pokédex trackers of the older generations, such as
- [ ] Diamond / Pearl / Platine
- [ ] HeartGold / SoulSilver
- [ ] Ruby / Saphir / Emerald

**Comment by Azekthi** [comment] 2021-05-10 21:37
Duplicate of #264

**Closed** 2022-02-09 00:42 UTC
