### ISSUE TITLE
Feature Request: Home national dex option without forms

### ISSUE THREAD

**Issue by CameronBun** [pokedextracker/pokedextracker.com#466] opened 2022-08-29 12:15 UTC
Pretty simple one, personally i'm not aiming to have all the forms just to fill out the dex numbers. Love using this to track my progress but would love to send to my friends just getting into pokemon without having to explain the big empty section at the end. Also will help to see progress at a glance without having to mentally remove the extras past 905.

**Comment by j3nesis87** [comment] 2022-11-22 13:41
Agreed, I'd love to see the Home National Dex with the option to remove forms. Maybe split out into include/exclude Galarian, Alolan, Gigantamax, Dynamax, Hisuan as options.

**Comment by ami** [comment] 2023-06-04 02:11
closing, dupe of: https://github.com/pokedextracker/pokedextracker.com/issues/267

**Closed by ami** 2023-06-04 02:11 UTC
